### ISSUE TITLE
Request for detailed document

### ISSUE THREAD

**Issue by BrikerMan** [matthyx/kong-elastic-apm#1]
We are using kong ingress in k8s cluster. Can you kindly provide more detailed document about how to integrate this with our kong-ingress. 

Thanks a lot for the great work.

**Comment by matthyx** [comment]
Hi @BrikerMan sure thing, this repo was just to register to the Kong hackathon.
The solution in that repo has pretty bad scalability because it relies on the gateway plugin... and does synchronous calls during the packet handling.
Together with @ludovic-pourrat we have made a second implementation which adds tracing data afterwards using the logging phase handler (which is async).
I can check with him whether we should opensource it and provide some docs.

**Comment by matthyx** [comment]
So, I have checked with @ludovic-pourrat and we have done nothing more than what is described here:
https://docs.konghq.com/gateway/2.7.x/reference/external-plugins/

As for publishing the new version (with improved performance) we have to wait approval from the newly created OSPO in our bank. I would not expect anything in the next 3 months unfortunately.

At least from a usage point of view, both plugins should deliver the same experience.

**Comment by matthyx** [comment]
Please let me know if `go build` doesn't work for you.

**Comment by BrikerMan** [comment]
Thanks for your reply. I will update you about `go build` next month.
We are preparing for the Chinese new year, so will be busy with other tasks till the end of next month. Is that okay I keep this issue open for 2 months?

**Comment by matthyx** [comment]
Sure, no problem. Happy new year!

**Comment by matthyx** [comment]
@BrikerMan I have added some resources, please check the README and docker-compose files.
